2021-06-12 20:03:55,196:__main__:division error
Traceback (most recent call last):
  File "/mnt/d/Python/python_socket/test.py", line 15, in cal_
    val = num1 / num2
ZeroDivisionError: division by zero
